#!/usr/bin/env bash
# ============================================================
# NotiFlow Local Development Setup
#
# Prerequisites:
#   - Docker Desktop running
#   - Node.js 18+
#
# Usage:
#   bash scripts/setup-local.sh
#
# What this does:
#   1. Starts local Supabase (Docker containers)
#   2. Runs migrations + seed data
#   3. Generates apps/web/.env.local with local keys
#   4. Prints instructions to start the web app
# ============================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SUPABASE_DIR="$ROOT_DIR/packages/supabase"
WEB_DIR="$ROOT_DIR/apps/web"
ENV_FILE="$WEB_DIR/.env.local"

echo "========================================"
echo " NotiFlow Local Dev Setup"
echo "========================================"

# 1. Check Docker
if ! docker info > /dev/null 2>&1; then
  echo "ERROR: Docker is not running. Start Docker Desktop first."
  exit 1
fi
echo "[1/4] Docker is running"

# 2. Start Supabase
echo "[2/4] Starting local Supabase..."
cd "$SUPABASE_DIR"
npx supabase start 2>&1 | tail -20

# 3. Get keys from supabase status
echo "[3/4] Reading local Supabase keys..."
SUPABASE_URL=$(npx supabase status --output json 2>/dev/null | grep -o '"API_URL":"[^"]*"' | cut -d'"' -f4)
ANON_KEY=$(npx supabase status --output json 2>/dev/null | grep -o '"ANON_KEY":"[^"]*"' | cut -d'"' -f4)
SERVICE_ROLE_KEY=$(npx supabase status --output json 2>/dev/null | grep -o '"SERVICE_ROLE_KEY":"[^"]*"' | cut -d'"' -f4)

if [ -z "$SUPABASE_URL" ] || [ -z "$ANON_KEY" ]; then
  echo "ERROR: Could not read Supabase keys. Try: npx supabase status -w packages/supabase"
  exit 1
fi

# 4. Generate .env.local (backup existing)
if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "$ENV_FILE.cloud-backup"
  echo "   Backed up existing .env.local → .env.local.cloud-backup"
fi

cat > "$ENV_FILE" << EOF
# ============================================================
# LOCAL DEVELOPMENT — Auto-generated by scripts/setup-local.sh
# To switch back to cloud: cp .env.local.cloud-backup .env.local
# ============================================================
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
PARSE_API_SECRET=local-dev-secret-12345

# AI keys (uncomment and set for AI parsing)
# GOOGLE_API_KEY=your-google-api-key
# ANTHROPIC_API_KEY=your-anthropic-api-key
# OPENAI_API_KEY=your-openai-api-key
EOF

echo "[4/4] Generated $ENV_FILE"

echo ""
echo "========================================"
echo " Setup Complete!"
echo "========================================"
echo ""
echo " Local Supabase:"
echo "   API:     $SUPABASE_URL"
echo "   Studio:  http://127.0.0.1:54323"
echo "   Inbucket (email): http://127.0.0.1:54324"
echo ""
echo " Test login:"
echo "   Email:    test@notiflow.local"
echo "   Password: test1234"
echo ""
echo " Start web app:"
echo "   npm run dev:web"
echo ""
echo " Restore cloud env:"
echo "   cp apps/web/.env.local.cloud-backup apps/web/.env.local"
echo ""
echo " Stop Supabase:"
echo "   npm run supabase:stop"
echo ""
